### PR TITLE
Changing all UPPERCASE variables to camelCase in lib/reporter.js

### PR DESCRIPTION
**Pull request by cosminj**
On a linux environment, javascript is case sensitive (https://www.safaribooksonline.com/library/view/javascript-the-definitive/0596000480/ch02s02.html)

Currently the code before reporter.js declares multiple variables using camelCase, while reporter.js refers to them as UPPERCASE global variables.
(https://github.com/search?utf8=✓&q=org%3AColdBox+specStats&type=Code)

On a npm version 6.1.0 this fails with all the declared variables as undefined.

### CODE REVIEW

**Comment by seancoyne** [comment]
Those come from CF and are always all caps. What CF engine are you on? I’m guessing Railo or Lucee with the nonstandard “remember struct case” feature enabled.

**Comment by cosminj** [comment]
It's the standard Adobe CF install for a Linux on Ubuntu 14.04. Is there a way to disable that default "remember struct case"? That would be much better! Thanks!

**Comment by seancoyne** [comment]
What version of CF? I'd assume its a setting in the CF admin but I don't recall if ACF has that same feature.

**Comment by cosminj** [comment]
It's CF 2016. I couldn't find such a setting in CF Admin, but maybe my eyes are weak :)

**Pull request closed without merging**
